from PyQt5.QtWidgets import QVBoxLayout,QHBoxLayout,QWidget,QMainWindow,QLineEdit,QPushButton,QLabel,QApplication,QComboBox
from PyQt5.QtGui import QPixmap,QIcon,QFont
import webbrowser,sys,os,googlesearch

os.chdir("C:/Users/asus/Desktop/Sample Picture")

class Window(QMainWindow):
    def __init__(self):
        super().__init__()
        self.program()
        
    def program(self):
        self.pencere=QWidget()
        self.pencere.setStyleSheet("Background:black")
        self.pencere.setWindowTitle("Browser")
        self.Text=QLineEdit()
        self.Text.setStyleSheet("Background:lightgray")
        self.Text.setMaximumHeight(75)
        self.Text.setFont(QFont('Arial',24,weight=3))
        self.search=QPushButton("Search")
        self.search.setFont(QFont('Arial',20,weight=3))
        self.search.setStyleSheet("Background:green")
        
        self.clear=QPushButton("Clear")
        self.clear.setFont(QFont('Arial',20,weight=3))
        self.clear.setStyleSheet("Background:red")
        self.Image=QLabel()
        self.Image.setPixmap(QPixmap("Google2.png"))
        self.Image.setStyleSheet("Background: Black")
        v_box=QVBoxLayout()
        h_box=QHBoxLayout()
        h_box2=QHBoxLayout()
        h_box2.addStretch()
        
        h_box2.addWidget(self.Image)
        h_box2.addStretch()
        v_box.addStretch()
        v_box.addLayout(h_box2)
        v_box.addSpacing(10)
        h_box.addSpacing(150)
        h_box.addWidget(self.Text)
        h_box.addSpacing(5)
        h_box.addWidget(self.search)
        h_box.addSpacing(5)
        h_box.addWidget(self.clear)
        h_box.addSpacing(150)
        v_box.addLayout(h_box)
        v_box.addStretch()
        self.pencere.setLayout(v_box)
        self.clear.clicked.connect(self.browser)
        self.search.clicked.connect(self.browser)
        self.pencere.show()
        
        
    def browser(self):
        sender=self.pencere.sender()
        if sender.text()=="Search":
            """chrome=webbrowser.Chrome("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe")
            chrome.open_new_tab(str(self.Text.text()))
            self.Text.clear()"""
            query=self.Text.text()
            self.a=list()
            for j in googlesearch.search(query, tld="co.in", num=100, stop=100, pause=2):
              self.a.append(j)
              self.program2()
        elif sender.text()=="Clear":
            self.Text.clear()
    
    def program2(self):
        
        self.pencere.close()
        self.pencere2=QWidget()
        self.pencere2.setWindowTitle("Browser")
        self.pencere2.setStyleSheet("Background:Black")
        self.Image2=QLabel()
        self.Image2.setPixmap(QPixmap("Google2.png"))
        self.liste=QComboBox()
        self.liste.setStyleSheet("Background:lightblue")
        self.liste.setMaximumHeight(80)
        self.liste.addItems(self.a)
        self.back=QPushButton("<")
        self.back.setStyleSheet("Background: Red")
        self.go=QPushButton("Enter")
        self.go.setStyleSheet("Background:Green")
        self.go.setMaximumHeight(50)
        v_box=QVBoxLayout()
        h_box3=QHBoxLayout()
        h_box=QHBoxLayout()
        h_box2=QHBoxLayout()
        h_box3.addWidget(self.back)
        h_box3.addStretch()
        h_box2.addStretch()
        h_box2.addWidget(self.Image2)
        h_box2.addStretch()
        h_box.addStretch()
        h_box.addWidget(self.liste)
        h_box.addSpacing(5)
        h_box.addWidget(self.go)
        h_box.addStretch()
        v_box.addLayout(h_box3)
        v_box.addStretch()
        v_box.addSpacing(50)
        v_box.addLayout(h_box2)
        v_box.addSpacing(10)
        v_box.addLayout(h_box)
        v_box.addStretch()
        
        self.pencere2.setLayout(v_box)
        self.pencere2.show()
        self.go.clicked.connect(self.google)
        self.back.clicked.connect(self.program3)
        
    def program3(self):
        self.pencere2.close()
        self.pencere=QWidget()
        self.pencere.setStyleSheet("Background:black")
        self.pencere.setWindowTitle("Browser")
        self.Text=QLineEdit()
        self.Text.setStyleSheet("Background:lightgray")
        self.Text.setMaximumHeight(75)
        self.Text.setFont(QFont('Arial',24,weight=3))
        self.search=QPushButton("Search")
        self.search.setFont(QFont('Arial',20,weight=3))
        self.search.setStyleSheet("Background:green")
        self.back=QPushButton("<")
        self.back.setStyleSheet("Background: Red")
        self.clear=QPushButton("Clear")
        self.clear.setFont(QFont('Arial',20,weight=3))
        self.clear.setStyleSheet("Background:red")
        self.Image=QLabel()
        self.Image.setPixmap(QPixmap("Google2.png"))
        self.Image.setStyleSheet("Background: Black")
        v_box=QVBoxLayout()
        h_box=QHBoxLayout()
        h_box2=QHBoxLayout()
        h_box3=QHBoxLayout()
        h_box3.addWidget(self.back)
        h_box3.addStretch()
        h_box2.addStretch()
        
        h_box2.addWidget(self.Image)
        h_box2.addStretch()
        v_box.addLayout(h_box3)
        v_box.addStretch()
        v_box.addSpacing(30)
        v_box.addLayout(h_box2)
        v_box.addSpacing(10)
        h_box.addSpacing(150)
        h_box.addWidget(self.Text)
        h_box.addSpacing(5)
        h_box.addWidget(self.search)
        h_box.addSpacing(5)
        h_box.addWidget(self.clear)
        h_box.addSpacing(150)
        v_box.addLayout(h_box)
        v_box.addStretch()
        self.pencere.setLayout(v_box)
        self.clear.clicked.connect(self.browser)
        self.search.clicked.connect(self.browser)
        self.back.clicked.connect(self.program2)
        self.pencere.show()
                
    def google(self):
        sender=self.pencere2.sender()
        if sender.text()=="Enter":
         chrome=webbrowser.Chrome("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe")
         chrome.open_new_tab(str(self.liste.currentText()))  
         
              
app=QApplication(sys.argv)
app.setWindowIcon(QIcon("Google.png"))
window=Window()

sys.exit(app.exec())