from datetime import datetime
from PyQt5 import QtGui
from PyQt5.QtWidgets import QMainWindow,QHBoxLayout,QApplication,QLabel,QVBoxLayout,QLineEdit,QPushButton,QWidget,QRadioButton,QFileDialog
import sys,sqlite3,random,os
class Pencere(QMainWindow):
     def __init__(self):
        super().__init__()
        self.init_ui()

     def init_ui(self):

      self.windows2=QWidget()
      self.windows2.setWindowTitle("Okul Kaydı")
      self.windows2.setMinimumSize(300,300)
      self.Yazı=QLabel("Programa Hoşgeldiniz")
      self.Yazı2=QLabel(str(datetime.ctime(datetime.now())))
      self.Yazı3=QLabel("---Kategoriler---")
      self.Yazı4=QLabel("1-Öğrenci\n2-Öğretmen\n3-Personel")
      self.öğrenci=QRadioButton(" Öğrenci")
      self.öğretmen=QRadioButton(" Öğretmen")
      self.personel=QRadioButton(" Personel")
      self.buton=QPushButton("Onayla")
      v_box=QVBoxLayout()
      h_box=QHBoxLayout()
      v_box.addStretch()
      v_box.addWidget(self.Yazı)
      v_box.addWidget(self.Yazı2)
      v_box.addWidget(self.Yazı3)
      v_box.addWidget(self.Yazı4)
      v_box.addWidget(self.öğrenci)
      v_box.addWidget(self.öğretmen)
      v_box.addWidget(self.personel)
      v_box.addWidget(self.buton)
      v_box.addStretch()
      v_box.maximumSize()
      h_box.addStretch()
      h_box.addLayout(v_box)
      h_box.addStretch()
      h_box.maximumSize()
      self.windows2.setLayout(h_box)
      self.windows2.show()
      
      self.buton.clicked.connect(lambda : self.Kategori(self.öğrenci.isChecked(),self.öğretmen.isChecked(),self.personel.isChecked()))

     def Kategori(self,öğrenci,öğretmen,personel):

       if öğrenci==1:

         self.windows2.close()
         self.windows=QWidget()
         self.Yazı5=QLabel("---Yapmak İstediğiniz İşlemi Seçiniz---")
         self.gosterme=QRadioButton("Kayıtları Gösterme")
         self.ekleme=QRadioButton("Kayıt Ekleme")
         self.sorgulama=QRadioButton("Kayıt Sorgulama")
         self.güncelle=QRadioButton("Kayıdı Güncelle")
         self.sil=QRadioButton("Kayıdı Sil")
         self.buton3=QPushButton("Onayla")
         self.buton4=QPushButton("<")
         v_box=QVBoxLayout()
         v_box.addWidget(self.buton4)
         v_box.addWidget(self.Yazı5)
         v_box.addWidget(self.gosterme)
         v_box.addWidget(self.ekleme)
         v_box.addWidget(self.sorgulama)
         v_box.addWidget(self.güncelle)
         v_box.addWidget(self.sil)
         v_box.addStretch()
         v_box.addWidget(self.buton3)
         self.windows.setLayout(v_box)
         self.windows.setWindowTitle("İşlem Seçimi")
         self.buton4.clicked.connect(self.Entrance2)
         self.buton3.clicked.connect(lambda : self.Ogrenci(self.gosterme.isChecked(),self.ekleme.isChecked(),self.sorgulama.isChecked(),self.güncelle.isChecked(),self.sil.isChecked()))
         self.windows.show()

       elif öğretmen==1:

         self.windows2.close()
         self.windows=QWidget()
         self.Yazı5=QLabel("---Yapmak İstediğiniz İşlemi Seçiniz---")
         self.gosterme=QRadioButton("Kayıtları Gösterme")
         self.ekleme=QRadioButton("Kayıt Ekleme")
         self.sorgulama=QRadioButton("Kayıt Sorgulama")
         self.güncelle=QRadioButton("Kayıdı Güncelle")
         self.sil=QRadioButton("Kayıdı Sil")
         self.buton3=QPushButton("Onayla")
         self.buton4=QPushButton("<")
         v_box=QVBoxLayout()
         v_box.addWidget(self.buton4)
         v_box.addWidget(self.Yazı5)
         v_box.addWidget(self.gosterme)
         v_box.addWidget(self.ekleme)
         v_box.addWidget(self.sorgulama)
         v_box.addWidget(self.güncelle)
         v_box.addWidget(self.sil)
         v_box.addStretch()
         v_box.addWidget(self.buton3)
         self.windows.setLayout(v_box)
         self.windows.setWindowTitle("İşlem Seçimi")
         self.buton4.clicked.connect(self.Entrance2)
         self.buton3.clicked.connect(lambda : self.Ogretmen(self.gosterme.isChecked(),self.ekleme.isChecked(),self.sorgulama.isChecked(),self.güncelle.isChecked(),self.sil.isChecked()))
         self.windows.show()

       elif personel==1:

         self.windows2.close()
         self.windows=QWidget()
         self.Yazı5=QLabel("---Yapmak İstediğiniz İşlemi Seçiniz---")
         self.gosterme=QRadioButton("Kayıtları Gösterme")
         self.ekleme=QRadioButton("Kayıt Ekleme")
         self.sorgulama=QRadioButton("Kayıt Sorgulama")
         self.güncelle=QRadioButton("Kayıdı Güncelle")
         self.sil=QRadioButton("Kayıdı Sil")
         self.buton3=QPushButton("Onayla")
         self.buton4=QPushButton("<")
         v_box=QVBoxLayout()
         v_box.addWidget(self.buton4)
         v_box.addWidget(self.Yazı5)
         v_box.addWidget(self.gosterme)
         v_box.addWidget(self.ekleme)
         v_box.addWidget(self.sorgulama)
         v_box.addWidget(self.güncelle)
         v_box.addWidget(self.sil)
         v_box.addStretch()
         v_box.addWidget(self.buton3)
         self.windows.setLayout(v_box)
         self.windows.setWindowTitle("İşlem Seçimi")
         self.buton4.clicked.connect(self.Entrance2)
         self.buton3.clicked.connect(lambda : self.Personel(self.gosterme.isChecked(),self.ekleme.isChecked(),self.sorgulama.isChecked(),self.güncelle.isChecked(),self.sil.isChecked()))
         self.windows.show()


     def Ogrenci(self,gosterme,ekleme,sorgulama,güncelleme,silme):
          if gosterme==1:
            self.windows.close()
            self.windows3=QWidget()
            self.windows3.setWindowTitle("Öğrenci Kayıtlarını Gösterme")
            self.buton5=QPushButton(">")
            con4=sqlite3.connect("Ogrenci.db")
            cursor4=con4.cursor()
            cursor4.execute("Select * From Ogrenci")
            kayıt=cursor4.fetchall()
            v_box=QVBoxLayout()
            h_box=QHBoxLayout()
            h_box2=QHBoxLayout()
            h_box.addWidget(self.buton5)
            self.write=QLabel()
            v_box.addLayout(h_box)
            h_box2.addStretch()
            h_box2.addWidget(self.write)
            h_box2.addStretch()
            v_box.addSpacing(70)
            v_box.addLayout(h_box2)
            self.write.setFont(QtGui.QFont('Arial Font ',40))
            self.windows3.setLayout(v_box)
            if kayıt==0:
              self.write.setText("Kayıt Bulunmamaktadır.")
              con4.close()
            else:
              self.write.setText("Kayıt Dosyası Masaüstüne İnmiştir.")
              os.chdir("C:/Users/atabe/OneDrive/Masaüstü")
              with open ("Öğrenciler.txt","w",encoding="utf-8") as file:
               for i in range(0,len(kayıt)):
                file.write(str(i+1))
                file.write(")")
                file.write("\t")
                file.write(str(kayıt[i]))
                file.write("\n")
              con4.close()   
            self.windows3.show()
            self.buton5.clicked.connect(self.Shutdown)
          elif ekleme==True:
           self.windows.close()
           self.windows3=QWidget()
           self.windows3.setWindowTitle("Öğrenci Kayıt Ekleme")
           self.Name=QLabel("Ad:")
           self.Ad2=QLineEdit()
           self.Surname=QLabel("Soyad:")
           self.soyad2=QLineEdit()
           self.TC=QLabel("TC Kimlik Numarası:")
           self.Tc2=QLineEdit()
           self.DY=QLabel("Doğum Tarihi:")
           self.Dy2=QLineEdit()
           self.TEL=QLabel("Öğrencinin Velisinin Telefon Numarası: ")
           self.Tel2=QLineEdit()
           self.buton2=QPushButton("Kaydet")
           h_box7=QHBoxLayout()
           self.buton4=QPushButton("<")
           self.buton5=QPushButton(">")
           h_box7.addWidget(self.buton4)
           h_box7.addWidget(self.buton5)
           v_box=QVBoxLayout()
           h_box=QHBoxLayout()
           h_box.addWidget(self.Name)
           h_box.addWidget(self.Ad2)
       
           h_box2=QHBoxLayout()
           h_box2.addWidget(self.Surname)
           h_box2.addWidget(self.soyad2)
       
           h_box3=QHBoxLayout()
           h_box3.addWidget(self.TC)
           h_box3.addWidget(self.Tc2)

           h_box4=QHBoxLayout()
           h_box4.addWidget(self.DY)
           h_box4.addWidget(self.Dy2)
           self.yazı_alanı=QLabel(" ")
           h_box5=QHBoxLayout()
           h_box5.addWidget(self.TEL)
           h_box5.addWidget(self.Tel2)
           v_box.addLayout(h_box7)
           v_box.addLayout(h_box)
           v_box.addLayout(h_box2)
           v_box.addLayout(h_box3)
           v_box.addLayout(h_box4)
           v_box.addLayout(h_box5)
           v_box.addWidget(self.yazı_alanı)
           v_box.addWidget(self.buton2)
           self.windows3.setLayout(v_box)
           self.buton2.clicked.connect(self.sql)
           self.buton4.clicked.connect(self.Category)
           self.buton5.clicked.connect(self.Entrance)
           self.windows3.show()

          elif sorgulama==1:
            self.windows.close()
            self.windows4=QWidget()
            self.Name3=QLabel("Öğrencinin Adı:")
            self.Ad6=QLineEdit()
            self.Surname3=QLabel(" Öğrencinin Soyadı:")
            self.soyad6=QLineEdit()
            self.buton6=QPushButton("Sorgula")
            self.buton4=QPushButton("<")
            self.buton5=QPushButton(">")
            h_box12=QHBoxLayout()
            self.yazı_alanı3=QLabel("")
            h_box12.addWidget(self.yazı_alanı3)
            h_box11=QHBoxLayout()
            h_box11.addWidget(self.buton4)
            h_box11.addWidget(self.buton5)
            h_box8=QHBoxLayout()
            h_box8.addWidget(self.Name3)
            h_box8.addWidget(self.Ad6)
            h_box9=QHBoxLayout()
            h_box9.addWidget(self.Surname3)
            h_box9.addWidget(self.soyad6)
            h_box10=QHBoxLayout()
            h_box10.addWidget(self.buton6)
            v_box2=QVBoxLayout()
            v_box2.addLayout(h_box11)
            v_box2.addLayout(h_box8)
            v_box2.addLayout(h_box9)
            v_box2.addLayout(h_box10)
            v_box2.addLayout(h_box12)
            self.windows4.setWindowTitle("Öğrenci Kayıt Sorgulama")
            self.buton4.clicked.connect(self.Category4)
            self.buton5.clicked.connect(self.Entrance3)
            self.buton6.clicked.connect(self.sql4)
            self.windows4.setLayout(v_box2)
            self.windows4.show()

          elif güncelleme==1:
           self.windows.close()
           self.windows7=QWidget()
           self.TC=QLabel("Öğrenci TC Kimlik Numarasını Yazınız: ")
           self.Tc4=QLineEdit()
           self.buton7=QPushButton("Sorgula")
           self.buton4=QPushButton("<")
           
           self.yazı_alanı4=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc4)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           v_box3.addWidget(self.yazı_alanı4)
           v_box3.addWidget(self.buton7)
           self.windows7.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category7)
           self.buton7.clicked.connect(self.sql25)
           self.windows7.setWindowTitle("Öğrenci Kaydı Güncelleme")
           self.windows7.show()

          elif silme==1:
           self.windows.close()
           self.windows7=QWidget()
           self.TC=QLabel("Öğrencinin TC Kimlik Numarasını Yazınız: ")
           self.Tc5=QLineEdit()
           
           self.buton7=QPushButton("Sil")
           self.buton4=QPushButton("<")
           self.buton5=QPushButton(">")
           self.yazı_alanı11=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
          
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           h_box14.addWidget(self.buton5)
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc5)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           
           v_box3.addWidget(self.yazı_alanı11)
           v_box3.addWidget(self.buton7)
           self.windows7.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category7)
           self.buton5.clicked.connect(self.Entrance4)
           self.buton7.clicked.connect(self.sql16)
           self.windows7.setWindowTitle("Öğrenci Kaydı Silme")
           self.windows7.show()
      
     def sql25(self):
           con=sqlite3.connect("Ogrenci.db")
           cursor=con.cursor()
           cursor.execute("Select * From Ogrenci Where Tc=? ",(self.Tc4.text(),))
           kayıt5=cursor.fetchone()
           if kayıt5!=None:
            self.yazı_alanı4.setText(str(kayıt5))
            self.Category11()
            con.close()
           else:
            self.yazı_alanı4.setText("Girilen Tc Numarasına Sahip Olan Öğrenci Bulunmamaktadır.")
            self.Tc4.clear()
            cursor.execute("Select * From Ogrenci Where Tc=? ",(self.Tc4.text(),))
            kayıt5=cursor.fetchone()
     def dosya(self):
      with open("Ogrenciler.txt","r",encoding="utf-8") as file:
        os.chdir("C:/Users/atabe/OneDrive/Masaüstü")
        file=QFileDialog.getOpenFileName(self,"Kayıtları Göster",os.getenv("ataberk köroğlu"))
        with open(file[0],"r+")as file:
          pass
     def sql26(self):
      con=sqlite3.connect("Ogrenci.db")
      cursor=con.cursor()
      cursor.execute("Update Ogrenci set Ad=? where Tc=?",(self.New_Ad.text(),self.Tc4.text()))
      con.commit()
      cursor.execute("Select * From Ogrenci Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor.fetchone()
      if kayıt!=None:
        self.yazı_alanı5.setText(str(kayıt))
        con.close()
      else:
        self.yazı_alanı5.setText("Ad Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Ad.clear()
        cursor.execute("Update Ogrenci set Ad=? where Tc=?",(self.New_Ad.text(),self.Tc4.text()))
        con.commit()
      
     def sql27(self):
      con=sqlite3.connect("Ogrenci.db")
      cursor=con.cursor()
      cursor.execute("Update Ogrenci set Soyad=? where Tc=?",(self.New_Soyad.text(),self.Tc4.text()))
      con.commit()
      cursor.execute("Select * From Ogrenci Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor.fetchone()
      if kayıt!=None:
        self.yazı_alanı6.setText(str(kayıt))
        con.close()
      else:
        self.yazı_alanı6.setText("Soyad Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Ad.clear()
        cursor.execute("Update Ogrenci set Soyad=? where Tc=?",(self.New_Soyad.text(),self.Tc4.text()))
        con.commit()

     def sql28(self):
      con=sqlite3.connect("Ogrenci.db")
      cursor=con.cursor()
      cursor.execute("Update Ogrenci set Tc=? where Tc=?",(self.New_Tc.text(),self.Tc4.text()))
      con.commit()
      cursor.execute("Select * From Ogrenci Where Tc=?",(self.New_Tc.text(),))
      self.Tc4=self.New_Tc
      kayıt=cursor.fetchone()
      if kayıt!=None:
        self.yazı_alanı7.setText(str(kayıt))
        con.close()
      else:
        self.yazı_alanı7.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Tc.clear()
        cursor.execute("Update Ogrenci set Tc=? where Tc=?",(self.New_Tc.text(),self.Tc4.text()))
        con.commit()

     def sql29(self):
      con=sqlite3.connect("Ogrenci.db")
      cursor=con.cursor()
      cursor.execute("Update Ogrenci set Dy=? where Tc=?",(self.New_Dy.text(),self.Tc4.text()))
      con.commit()
      cursor.execute("Select * From Ogrenci Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor.fetchone()
      if kayıt!=None:
        self.yazı_alanı8.setText(str(kayıt))
        con.close()
      else:
        self.yazı_alanı8.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Tc.clear()
        cursor.execute("Update Ogrenci set Dy=? where Tc=?",(self.New_Dy.text(),self.Tc4.text()))
        con.commit()
     
     def sql30(self):
      con=sqlite3.connect("Ogrenci.db")
      cursor=con.cursor()
      cursor.execute("Update Ogrenci set Tel=? where Tc=?",(self.New_Tel.text(),self.Tc4.text()))
      con.commit()
      cursor.execute("Select * From Ogrenci Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor.fetchone()
      if kayıt!=None:
        self.yazı_alanı9.setText(str(kayıt))
        con.close()
      else:
        self.yazı_alanı9.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Tc.clear()
        cursor.execute("Update Ogrenci set Tel=? where Tc=?",(self.New_Tel.text(),self.Tc4.text()))
        con.commit()

     def sql31(self):
      con=sqlite3.connect("Ogrenci.db")
      cursor=con.cursor()
      cursor.execute("Update Ogrenci set No=? where Tc=?",(self.New_No.text(),self.Tc4.text()))
      con.commit()
      cursor.execute("Select * From Ogrenci Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor.fetchone()
      if kayıt!=None:
        self.yazı_alanı10.setText(str(kayıt))
        con.close()
      else:
        self.yazı_alanı10.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_No.clear()
        cursor.execute("Update Ogrenci set No=? where Tc=?",(self.New_No.text(),self.Tc4.text()))
        con.commit()
     def sql16(self):
        con=sqlite3.connect("Ogrenci.db")
        cursor=con.cursor()
        cursor.execute("Select * From Ogrenci Where Tc=?",(self.Tc5.text(),))
        kayıt=cursor.fetchone()
        if kayıt==None:
          self.yazı_alanı11.setText("Bu TC Kimlik Numarasına Sahip Olan Öğrenci Bulunmamaktadır.")
          self.Tc5.clear()
        else:
          cursor.execute("Delete From Ogrenci Where Tc=?",(self.Tc5.text(),))
          con.commit()
          self.yazı_alanı11.setText("İşlem Başarıyla Gerçekleştirildi.")
          con.close()

     def sql(self):
        con=sqlite3.connect("Ogrenci.db")
        cursor=con.cursor()
        cursor.execute("Select * From Ogrenci Where Tc=?",(self.Tc2.text(),))
        kayıt=cursor.fetchone()
        No=random.randint(0,1000)

        if kayıt==None:

         cursor.execute("Insert Into Ogrenci(Ad,Soyad,Tc,Dy,Tel,No) Values(?,?,?,?,?,?)",(self.Ad2.text(),self.soyad2.text(),self.Tc2.text(),self.Dy2.text(),self.Tel2.text(),No))
         con.commit()
         self.yazı_alanı.setText("Kayıt Başarıyla Gerçekleşti.")   
         con.close()

        elif kayıt!=None:
            self.yazı_alanı.setText("Girdiğiniz Bilgilere Sahip Olan Öğrenci Kayıtlarda Bulunmaktadır.")          
            self.Ad2.clear()
            self.soyad2.clear()
            self.Tc2.clear()
            self.Dy2.clear()
            self.Tel2.clear()
            cursor.execute("Select * From Ogrenci Where Tc=?",(self.Tc2.text(),))
            kayıt=cursor.fetchone()
            No=random.randint(0,1000)
     def Shutdown(self):
        self.windows3.close()
        self.Entrance2()
     def Ogrenci_Guncelleme(self,ad,soyad,tc,dy,tel,no):

        if ad==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Name=QLabel("Yeni Adı:")
          self.New_Ad=QLineEdit()
          self.yazı_alanı5=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Name)
          h_box2.addWidget(self.New_Ad)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı5)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğrencinin  Adını Değiştirme")
          self.buton15.clicked.connect(self.sql26)
          self.buton4.clicked.connect(self.Category11)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()

        elif soyad==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Soyadı:")
          self.New_Soyad=QLineEdit()
          self.yazı_alanı6=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Soyad)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı6)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğrencinin  Soyadını Değiştirme")
          self.buton15.clicked.connect(self.sql27)
          self.buton4.clicked.connect(self.Category11)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif tc==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Tc Kimlik Numarası:")
          self.New_Tc=QLineEdit()
          self.yazı_alanı7=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Tc)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı7)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğrencinin  TC Kimlik Numarasını  Değiştirme")
          self.buton15.clicked.connect(self.sql28)
          self.buton4.clicked.connect(self.Guncelle6)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif dy==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Doğum Tarihi:")
          self.New_Dy=QLineEdit()
          self.yazı_alanı8=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Dy)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı8)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğrencinin  Doğum Tarihini Değiştirme")
          self.buton15.clicked.connect(self.sql29)
          self.buton4.clicked.connect(self.Category11)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif tel==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Cep Telefon Numarası:")
          self.New_Tel=QLineEdit()
          self.yazı_alanı9=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Tel)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı9)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğrenci Velisinin Cep Telefon Numarasını Değiştirme")
          self.buton15.clicked.connect(self.sql30)
          self.buton4.clicked.connect(self.Category11)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif no==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Okul Numarası:")
          self.New_No=QLineEdit()
          self.yazı_alanı10=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_No)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı10)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğrencinin Okul Numarasını Değiştirme")
          self.buton15.clicked.connect(self.sql31)
          self.buton4.clicked.connect(self.Category11)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()

     def Ogretmen(self,gosterme,ekleme,sorgulama,güncelle,sil):

         if gosterme==1:
            self.windows.close()
            self.windows3=QWidget()
            self.windows3.setWindowTitle("Öğretmen Kayıtlarını Gösterme")
            
            self.buton5=QPushButton(">")
           
            
            con2=sqlite3.connect("Ogretmen.db")
            cursor2=con2.cursor()
            cursor2.execute("Select * From Ogretmen")
            kayıt=cursor2.fetchall()
            v_box=QVBoxLayout()
            h_box=QHBoxLayout()
            h_box2=QHBoxLayout()
           
            h_box.addWidget(self.buton5)
            
            self.write=QLabel()
            
            v_box.addLayout(h_box)
            h_box2.addStretch()
            h_box2.addWidget(self.write)
            h_box2.addStretch()
            v_box.addSpacing(70)
            v_box.addLayout(h_box2)
            self.write.setFont(QtGui.QFont('Arial Font ',40))
            
            self.buton5.clicked.connect(self.Shutdown)
            
            
            self.windows3.setLayout(v_box)
            if kayıt==0:
              self.write.setText("Kayıt Bulunmamaktadır.")
              con2.close()
            else:
              self.write.setText("Kayıt Dosyası Masaüstüne İnmiştir.")
              os.chdir("C:/Users/atabe/OneDrive/Masaüstü")
              with open ("Ogretmen.txt","w",encoding="utf-8") as file:
               for i in range(0,len(kayıt)):
                file.write(str(i+1))
                file.write(")")
                file.write("\t")
                file.write(str(kayıt[i]))
                file.write("\n")
                
            self.windows3.show()

         elif ekleme==True:
           self.windows.close()
           self.windows3=QWidget()
           self.windows3.setWindowTitle("Öğretmen Kayıt Ekleme")
           self.Name=QLabel("Ad:")
           self.Ad=QLineEdit()
           self.Surname=QLabel("Soyad:")
           self.soyad=QLineEdit()
           self.TC=QLabel("TC Kimlik Numarası:")
           self.Tc=QLineEdit()
           self.DY=QLabel("Doğum Tarihi:")
           self.Dy=QLineEdit()
           self.TEL=QLabel("Öğretmenin Telefon Numarası: ")
           self.Tel=QLineEdit()
           self.Major=QLabel("Öğretmenin Branşı: ")
           self.bolum=QLineEdit()
           self.buton2=QPushButton("Kaydet")
           v_box=QVBoxLayout()
           h_box=QHBoxLayout()
           h_box7=QHBoxLayout()
           self.buton4=QPushButton("<")
           self.buton5=QPushButton(">")
           h_box7.addWidget(self.buton4)
           h_box7.addWidget(self.buton5)
           h_box.addWidget(self.Name)
           h_box.addWidget(self.Ad)
           self.yazı_alanı2=QLabel("")
           h_box2=QHBoxLayout()
           h_box2.addWidget(self.Surname)
           h_box2.addWidget(self.soyad)
       
           h_box3=QHBoxLayout()
           h_box3.addWidget(self.TC)
           h_box3.addWidget(self.Tc)

           h_box4=QHBoxLayout()
           h_box4.addWidget(self.DY)
           h_box4.addWidget(self.Dy)
       
           h_box5=QHBoxLayout()
           h_box5.addWidget(self.TEL)
           h_box5.addWidget(self.Tel)
           h_box6=QHBoxLayout()
           h_box6.addWidget(self.Major)
           h_box6.addWidget(self.bolum)
           v_box.addLayout(h_box7)
           v_box.addLayout(h_box)
           v_box.addLayout(h_box2)
           v_box.addLayout(h_box3)
           v_box.addLayout(h_box4)
           v_box.addLayout(h_box5)
           v_box.addLayout(h_box6)
           v_box.addWidget(self.yazı_alanı2)
           v_box.addWidget(self.buton2)
           self.windows3.setLayout(v_box)
           self.windows3.setWindowTitle("Öğretmen Kayıt Ekleme")
           self.buton2.clicked.connect(self.sql2)
           self.buton4.clicked.connect(self.Category2)
           self.buton5.clicked.connect(self.Entrance6)
           self.windows3.show()

         elif sorgulama==1:
            self.windows.close()
            self.windows4=QWidget()
            self.Name4=QLabel("Öğretmenin Adı:")
            self.Ad5=QLineEdit()
            self.Surname3=QLabel(" Öğretmenin Soyadı:")
            self.soyad5=QLineEdit()
            self.buton6=QPushButton("Sorgula")
            self.buton4=QPushButton("<")
            self.buton5=QPushButton(">")
            h_box11=QHBoxLayout()
            h_box11.addWidget(self.buton4)
            h_box11.addWidget(self.buton5)
            h_box8=QHBoxLayout()
            h_box8.addWidget(self.Name4)
            h_box8.addWidget(self.Ad5)
            h_box9=QHBoxLayout()
            h_box9.addWidget(self.Surname3)
            h_box9.addWidget(self.soyad5)
            h_box10=QHBoxLayout()
            h_box10.addWidget(self.buton6)
            h_box12=QHBoxLayout()
            self.yazı_alanı2=QLabel("")
            h_box12.addWidget(self.yazı_alanı2)
            v_box2=QVBoxLayout()
            v_box2.addLayout(h_box11)
            v_box2.addLayout(h_box8)
            v_box2.addLayout(h_box9)
            v_box2.addLayout(h_box10)
            v_box2.addLayout(h_box12)
            self.buton4.clicked.connect(self.Category5)
            self.buton5.clicked.connect(self.Entrance3)
            self.buton6.clicked.connect(self.sql5)
            self.windows4.setWindowTitle("Öğretmen Kayıt Sorgulama")
            self.windows4.setLayout(v_box2)
            self.windows4.show()
   
         elif güncelle==1:
           self.windows.close()
           self.windows7=QWidget()
           self.TC=QLabel("Öğretmenin TC Kimlik Numarasını Yazınız: ")
           self.Tc4=QLineEdit()
           self.buton7=QPushButton("Sorgula")
           self.buton4=QPushButton("<")
           self.buton5=QPushButton(">")
           self.yazı_alanı4=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           h_box14.addWidget(self.buton5)
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc4)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           v_box3.addWidget(self.yazı_alanı4)
           v_box3.addWidget(self.buton7)
           self.windows7.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category7)
           self.buton5.clicked.connect(self.Entrance4)
           self.buton7.clicked.connect(self.sql18)
           self.windows7.setWindowTitle("Öğretmen Kaydı Güncelleme")
           self.windows7.show()
           

         elif sil==1:
           self.windows.close()
           self.windows7=QWidget()
           self.TC=QLabel("Öğretmenin TC Kimlik Numarasını Yazınız: ")
           self.Tc5=QLineEdit()
           
           self.buton7=QPushButton("Sil")
           self.buton4=QPushButton("<")
           self.buton5=QPushButton(">")
           self.yazı_alanı11=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
          
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           h_box14.addWidget(self.buton5)
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc5)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           
           v_box3.addWidget(self.yazı_alanı11)
           v_box3.addWidget(self.buton7)
           self.windows7.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category7)
           self.buton5.clicked.connect(self.Entrance4)
           self.buton7.clicked.connect(self.sql15)
           self.windows7.setWindowTitle("Öğretmen Kaydı Silme")
           self.windows7.show()
      
     def sql18(self):
           con2=sqlite3.connect("Ogretmen.db")
           cursor2=con2.cursor()
           cursor2.execute("Select * From Ogretmen Where Tc=? ",(self.Tc4.text(),))
           kayıt5=cursor2.fetchone()
           if kayıt5!=None:
            self.yazı_alanı4.setText(str(kayıt5))
            self.Category9()
            con2.close()
           else:
            self.yazı_alanı4.setText("Girilen Tc Numarasına Sahip Olan Personel Bulunmamaktadır.")
            self.Tc4.clear()
            cursor2.execute("Select * From Ogretmen Where Tc=? ",(self.Tc4.text(),))
            kayıt5=cursor2.fetchone()
     def sql19(self):
      con3=sqlite3.connect("Ogretmen.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Ogretmen set Ad=? where Tc=?",(self.New_Ad.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Ogretmen Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı5.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı5.setText("Ad Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Ad.clear()
        cursor3.execute("Update Ogretmen set Ad=? where Tc=?",(self.New_Ad.text(),self.Tc4.text()))
        con3.commit()
      
     def sql20(self):
      con3=sqlite3.connect("Ogretmen.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Ogretmen set Soyad=? where Tc=?",(self.New_Soyad.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Ogretmen Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı6.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı6.setText("Soyad Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Ad.clear()
        cursor3.execute("Update Ogretmen set Soyad=? where Tc=?",(self.New_Soyad.text(),self.Tc4.text()))
        con3.commit()

     def sql21(self):
      con3=sqlite3.connect("Ogretmen.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Ogretmen set Tc=? where Tc=?",(self.New_Tc.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Ogretmen Where Tc=?",(self.New_Tc.text(),))
      self.Tc4=self.New_Tc
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı7.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı7.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Tc.clear()
        cursor3.execute("Update Ogretmen set Tc=? where Tc=?",(self.New_Tc.text(),self.Tc4.text()))
        con3.commit()

     def sql22(self):
      con3=sqlite3.connect("Ogretmen.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Ogretmen set Dy=? where Tc=?",(self.New_Dy.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Ogretmen Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı8.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı8.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Tc.clear()
        cursor3.execute("Update Ogretmen set Dy=? where Tc=?",(self.New_Dy.text(),self.Tc4.text()))
        con3.commit()
     
     def sql23(self):
      con3=sqlite3.connect("Ogretmen.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Ogretmen set Tel=? where Tc=?",(self.New_Tel.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Ogretmen Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı9.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı9.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Tc.clear()
        cursor3.execute("Update Ogretmen set Tel=? where Tc=?",(self.New_Tel.text(),self.Tc4.text()))
        con3.commit()

     def sql24(self):
      con3=sqlite3.connect("Ogretmen.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Ogretmen set Brans=? where Tc=?",(self.New_Brans.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Ogretmen Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı10.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı10.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Gorev.clear()
        cursor3.execute("Update Ogretmen set Brans=? where Tc=?",(self.New_Brans.text(),self.Tc4.text()))
        con3.commit()


     def sql15(self):
        con2=sqlite3.connect("Ogretmen.db")
        cursor2=con2.cursor()
        cursor2.execute("Select * From Ogretmen Where Tc=?",(self.Tc5.text(),))
        kayıt=cursor2.fetchone()
        if kayıt==None:
          self.yazı_alanı11.setText("Bu Tc Kimlik Numarasına Sahip Ogretmen Bulunmamaktadır.")
          self.Tc5.clear()
        else:
          cursor2.execute("Delete From Ogretmen Where Tc=?",(self.Tc5.text(),))
          con2.commit()
          self.yazı_alanı11.setText("İşlem Başarıyla Gerçekleştirildi.")
          con2.close()

     def sql2(self):
        con2=sqlite3.connect("Ogretmen.db")
        cursor2=con2.cursor()
        cursor2.execute("Select * From Ogretmen Where Tc=? or Tel=?",(self.Tc.text(),self.Tel.text()))
        kayıt2=cursor2.fetchone()
        if kayıt2==None:
         cursor2.execute("Insert Into Ogretmen(Ad,Soyad,Tc,Dy,Tel,Brans) Values(?,?,?,?,?,?)",(self.Ad.text(),self.soyad.text(),self.Tc.text(),self.Dy.text(),self.Tel.text(),self.bolum.text()))
         con2.commit()
         self.yazı_alanı2.setText("Kayıt Başarıyla Gerçekleşti.")   
         con2.close()
         
        elif kayıt2!=None:
            self.yazı_alanı2.setText("Girdiğiniz Bilgilere Sahip Olan Öğretmen Kayıtlarda Bulunmaktadır.")
            self.Ad.clear()
            self.soyad.clear()
            self.Tc.clear()
            self.Dy.clear()
            self.Tel.clear()
            self.bolum.clear()
            cursor2.execute("Select * From Ogretmen Where Tc=? or Tel=?",(self.Tc.text(),self.Tel.text()))
            kayıt2=cursor2.fetchone()

     def sql5(self):
        con2=sqlite3.connect("Ogretmen.db")
        cursor2=con2.cursor()
        cursor2.execute("Select * From Ogretmen Where Ad=? and Soyad=?",(self.Ad5.text(),self.soyad5.text()))
        kayıt2=cursor2.fetchone()
        if kayıt2==None:
          self.yazı_alanı2.setText("Girilen Bilgilere Göre Böyle Bir Öğretmen Bulunmamaktadır")
        elif kayıt2!=None:
          self.yazı_alanı2.setText(str(kayıt2))
     def sql4(self):
        con=sqlite3.connect("Ogrenci.db")
        cursor=con.cursor()
        cursor.execute("Select * From Ogrenci Where Ad=? and Soyad=?",(self.Ad6.text(),self.soyad6.text()))
        kayıt=cursor.fetchone()
        if kayıt==None:
          self.yazı_alanı3.setText("Girilen Bilgilere Göre Böyle Bir Öğrenci Bulunmamaktadır")
        elif kayıt!=None:
          self.yazı_alanı3.setText(str(kayıt))
     
     def Ogretmen_Güncelleme(self,ad,soyad,tc,dy,tel,brans):
        if ad==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Name=QLabel("Yeni Adı:")
          self.New_Ad=QLineEdit()
          self.yazı_alanı5=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Name)
          h_box2.addWidget(self.New_Ad)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı5)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğretmenin  Adını Değiştirme")
          self.buton15.clicked.connect(self.sql19)
          self.buton4.clicked.connect(self.Category9)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()

        elif soyad==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Soyadı:")
          self.New_Soyad=QLineEdit()
          self.yazı_alanı6=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Soyad)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı6)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğretmenin  Soyadını Değiştirme")
          self.buton15.clicked.connect(self.sql20)
          self.buton4.clicked.connect(self.Category9)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif tc==1:
          self.windows8.close()
          self.windows9=QWidget()
    
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Tc Kimlik Numarası:")
          self.New_Tc=QLineEdit()
          self.yazı_alanı7=QLabel("")
          self.buton4=QPushButton("<")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Tc)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı7)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)

          self.windows9.setWindowTitle("Öğretmenin  TC Kimlik Numarasını  Değiştirme:")
          self.buton15.clicked.connect(self.sql21)
          self.buton4.clicked.connect(self.Guncelle5)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif dy==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Doğum Tarihi:")
          self.New_Dy=QLineEdit()
          self.yazı_alanı8=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Dy)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı8)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğretmenin  Doğum Tarihini Değiştirme:")
          self.buton15.clicked.connect(self.sql22)
          self.buton4.clicked.connect(self.Category9)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif tel==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Cep Telefon Numarası:")
          self.New_Tel=QLineEdit()
          self.yazı_alanı9=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Tel)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı7)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğretmenin Cep Telefon Numarasını Değiştirme:")
          self.buton15.clicked.connect(self.sql23)
          self.buton4.clicked.connect(self.Category9)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif brans==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Branşı:")
          self.New_Brans=QLineEdit()
          self.yazı_alanı10=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Brans)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı10)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Öğretmenin Branşını Değiştirme:")
          self.buton15.clicked.connect(self.sql24)
          self.buton4.clicked.connect(self.Category10)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
            
     def Personel(self,gosterme,ekleme,sorgulama,güncelle,sil):

        if gosterme==1:
            self.windows.close()
            self.windows3=QWidget()
            self.windows3.setWindowTitle("Personel Kayıtlarını Gösterme")
            
            self.buton5=QPushButton(">")
           
            
            con3=sqlite3.connect("Personel.db")
            cursor3=con3.cursor()
            cursor3.execute("Select * From Personel")
            kayıt=cursor3.fetchall()
            v_box=QVBoxLayout()
            h_box=QHBoxLayout()
            h_box2=QHBoxLayout()
            
            h_box.addWidget(self.buton5)
            
            self.write=QLabel()
            
            v_box.addLayout(h_box)
            h_box2.addStretch()
            h_box2.addWidget(self.write)
            h_box2.addStretch()
            v_box.addSpacing(70)
            v_box.addLayout(h_box2)
            self.write.setFont(QtGui.QFont('Arial Font ',40))
            
            self.buton5.clicked.connect(self.Shutdown)
            self.windows3.setLayout(v_box)
            if kayıt==0:
              self.write.setText("Kayıt Bulunmamaktadır.")
              con3.close()
            else:
              self.write.setText("Kayıt Dosyası Masaüstüne İnmiştir.")
              os.chdir("C:/Users/atabe/OneDrive/Masaüstü")
              with open ("Personel.txt","w",encoding="utf-8") as file:
               for i in range(0,len(kayıt)):
                file.write(str(i+1))
                file.write(")")
                file.write("\t")
                file.write(str(kayıt[i]))
                file.write("\n")
              cursor3.execute("Select * From Personel")
              kayıt=cursor3.fetchall()
                 
                
            self.windows3.show()

        elif ekleme==True:
           self.windows.close()
           self.windows3=QWidget()
           self.windows3.setWindowTitle("Personel Kayıt Ekleme")
           self.Name=QLabel("Ad:")
           self.Ad3=QLineEdit()
           self.Surname=QLabel("Soyad:")
           self.soyad3=QLineEdit()
           self.TC=QLabel("TC Kimlik Numarası:")
           self.Tc3=QLineEdit()
           self.DY=QLabel("Doğum Tarihi:")
           
           self.Dy3=QLineEdit()
           self.TEL=QLabel("Personelin Telefon Numarası: ")
          
           self.Tel3=QLineEdit()
           self.Major=QLabel("Personelin Görevi: ")
          
           self.bolum3=QLineEdit()
           self.buton3=QPushButton("Kaydet")
           v_box=QVBoxLayout()
           h_box7=QHBoxLayout()
           self.buton4=QPushButton("<")
           self.buton5=QPushButton(">")
           h_box7.addWidget(self.buton4)
           h_box7.addWidget(self.buton5)
           h_box=QHBoxLayout()
           h_box.addWidget(self.Name)
           h_box.addWidget(self.Ad3)
           self.yazı_alanı3=QLabel("")
           h_box2=QHBoxLayout()
           h_box2.addWidget(self.Surname)
           h_box2.addWidget(self.soyad3)
       
           h_box3=QHBoxLayout()
           h_box3.addWidget(self.TC)
           h_box3.addWidget(self.Tc3)

           h_box4=QHBoxLayout()
           h_box4.addWidget(self.DY)
           h_box4.addWidget(self.Dy3)
       
           h_box5=QHBoxLayout()
           h_box5.addWidget(self.TEL)
           h_box5.addWidget(self.Tel3)
           h_box6=QHBoxLayout()
           h_box6.addWidget(self.Major)
           h_box6.addWidget(self.bolum3)
           v_box.addLayout(h_box7)
           v_box.addLayout(h_box)
           v_box.addLayout(h_box2)
           v_box.addLayout(h_box3)
           v_box.addLayout(h_box4)
           v_box.addLayout(h_box5)
           v_box.addLayout(h_box6)
           v_box.addWidget(self.yazı_alanı3)
           v_box.addWidget(self.buton3)
           self.windows3.setLayout(v_box)
           self.windows3.setWindowTitle("Personel Kayıt Ekleme")
           self.windows3.show()
           self.buton3.clicked.connect(self.sql3)
           self.buton4.clicked.connect(self.Category3)
           self.buton5.clicked.connect(self.Entrance)

        elif sorgulama==1:
            self.windows.close()
            self.windows4=QWidget()
            self.Name2=QLabel("Personelin Adı:")
            self.Ad4=QLineEdit()
            self.Surname2=QLabel("Personelin Soyadı:")
            self.soyad4=QLineEdit()
            self.buton6=QPushButton("Sorgula")
            self.buton4=QPushButton("<")
            self.buton5=QPushButton(">")
            self.yazı_alanı3=QLabel()
            h_box12=QHBoxLayout()
            h_box12.addWidget(self.yazı_alanı3)
            h_box11=QHBoxLayout()
            h_box11.addWidget(self.buton4)
            h_box11.addWidget(self.buton5)
            h_box8=QHBoxLayout()
            h_box8.addWidget(self.Name2)
            h_box8.addWidget(self.Ad4)
            h_box9=QHBoxLayout()
            h_box9.addWidget(self.Surname2)
            h_box9.addWidget(self.soyad4)
            h_box10=QHBoxLayout()
            h_box10.addWidget(self.buton6)
            v_box2=QVBoxLayout()
            v_box2.addLayout(h_box11)
            v_box2.addLayout(h_box8)
            v_box2.addLayout(h_box9)
            v_box2.addLayout(h_box10)
            v_box2.addLayout(h_box12)
            self.buton4.clicked.connect(self.Category6)
            self.buton5.clicked.connect(self.Entrance3)
            self.buton6.clicked.connect(self.sql6)
            self.windows4.setWindowTitle("Personel Kayıt Sorgulama")
            self.windows4.setLayout(v_box2)
            self.windows4.show()

        elif güncelle==1:
           self.windows.close()
           self.windows7=QWidget()
           self.TC=QLabel("Personelin TC Kimlik Numarasını Yazınız: ")
           self.Tc4=QLineEdit()
           self.buton7=QPushButton("Sorgula")
           self.buton4=QPushButton("<")
           
           self.yazı_alanı4=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc4)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           v_box3.addWidget(self.yazı_alanı4)
           v_box3.addWidget(self.buton7)
           self.windows7.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category7)
           
           self.buton7.clicked.connect(self.sql7)
           self.windows7.setWindowTitle("Personel Güncelleme")
           self.windows7.show()
           

        elif sil==1:
           self.windows.close()
           self.windows7=QWidget()
           self.TC=QLabel("Personelin TC Kimlik Numarasını Yazınız: ")
           self.Tc5=QLineEdit()
           
           self.buton7=QPushButton("Sil")
           self.buton4=QPushButton("<")
           self.buton5=QPushButton(">")
           self.yazı_alanı11=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
          
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           h_box14.addWidget(self.buton5)
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc5)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           
           v_box3.addWidget(self.yazı_alanı11)
           v_box3.addWidget(self.buton7)
           self.windows7.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category7)
           self.buton5.clicked.connect(self.Entrance4)
           self.buton7.clicked.connect(self.sql14)
           self.windows7.setWindowTitle("Personel Kaydı Silme")
           self.windows7.show()

     def sql14(self):
        con3=sqlite3.connect("Personel.db")
        cursor3=con3.cursor()
        
        cursor3.execute("Select * From Personel Where Tc=?",(self.Tc5.text(),))
        kayıt=cursor3.fetchone()
        if kayıt==None:
          self.yazı_alanı11.setText("Bu TC Kİmlik Numarasına Sahip Personel Bulunmamaktadır.")
          self.Tc5.clear()
          cursor3.execute("Delete From Personel Where Tc=?",(self.Tc5.text(),))
          con3.commit()
        else:
          cursor3.execute("Delete From Personel Where Tc=?",(self.Tc5.text(),))
          con3.commit()
          self.yazı_alanı11.setText("İşlem Başarıyla Tamamlandı.")
          con3.close()
          
        
     def sql7(self):
           con3=sqlite3.connect("Personel.db")
           cursor3=con3.cursor()
           cursor3.execute("Select * From Personel Where Tc=? ",(self.Tc4.text(),))
           kayıt5=cursor3.fetchone()
           if kayıt5!=None:
            self.yazı_alanı4.setText(str(kayıt5))
            self.Category8()
            con3.close()
           else:
            self.yazı_alanı4.setText("Girilen Tc Numarasına Sahip Olan Personel Bulunmamaktadır.")
            self.Tc4.clear()
            cursor3.execute("Select * From Personel Where Tc=? ",(self.Tc4.text(),))
            kayıt5=cursor3.fetchone()

     def sql6(self):
        con3=sqlite3.connect("Personel.db")
        cursor3=con3.cursor()
        cursor3.execute("Select * From Personel Where Ad=? and Soyad=?",(self.Ad4.text(),self.soyad4.text()))
        kayıt3=cursor3.fetchone()
        if kayıt3==None:
          self.yazı_alanı3.setText("Girilen Bilgilere Göre Böyle Bir Personel Bulunmamaktadır")
          con3.close()
        elif kayıt3!=None:
          self.yazı_alanı3.setText(str(kayıt3))
            

     def sql3(self):
        con3=sqlite3.connect("Personel.db")
        cursor3=con3.cursor()
        cursor3.execute("Select * From Personel Where Tc=? or Tel=?",(self.Tc3.text(),self.Tel3.text()))
        kayıt3=cursor3.fetchone()

        if kayıt3==None:
         cursor3.execute("Insert Into Personel(Ad,Soyad,Tc,Dy,Tel,Gorev) Values(?,?,?,?,?,?)",(self.Ad3.text(),self.soyad3.text(),self.Tc3.text(),self.Dy3.text(),self.Tel3.text(),self.bolum3.text()))
         con3.commit()
         self.yazı_alanı3.setText("Kayıt Başarıyla Gerçekleşti.")  
         con3.close()

        elif kayıt3!=None:
           self.yazı_alanı3.setText("Girdiğiniz Bilgilere Sahip Olan Personel Kayıtlarda Bulunmaktadır.")
           self.Ad3.clear()
           self.soyad3.clear()
           self.Tc3.clear()
           self.Dy3.clear()
           self.Tel3.clear()
           self.bolum3.clear()
           cursor3.execute("Select * From Personel Where Tc=? or Tel=?",(self.Tc3.text(),self.Tel3.text()))
           kayıt3=cursor3.fetchone()


     def Category(self):
         self.windows3.close()
         self.windows=QWidget()
         self.Yazı5=QLabel("---Yapmak İstediğiniz İşlemi Seçiniz---")
         self.gosterme=QRadioButton("Kayıt Gösterme")
         self.ekleme=QRadioButton("Kayıt Ekleme")
         self.sorgulama=QRadioButton("Kayıt Sorgulama")
         self.güncelle=QRadioButton("Kayıdı Güncelle")
         self.sil=QRadioButton("Kayıdı Sil")
         self.buton3=QPushButton("Onayla")
         self.buton4=QPushButton("<")
         h_box=QHBoxLayout()
         v_box=QVBoxLayout()
         h_box.addWidget(self.buton4)
         v_box.addLayout(h_box)
         v_box.addWidget(self.Yazı5)
         v_box.addWidget(self.gosterme)
         v_box.addWidget(self.ekleme)
         v_box.addWidget(self.sorgulama)
         v_box.addWidget(self.güncelle)
         v_box.addWidget(self.sil)
         v_box.addStretch()
         v_box.addWidget(self.buton3)
         self.windows.setLayout(v_box)
         self.windows.setWindowTitle("İşlem Seçimi")
         self.buton4.clicked.connect(self.Entrance2)
         
         self.buton3.clicked.connect(lambda : self.Ogrenci(self.gosterme.isChecked(),self.ekleme.isChecked(),self.sorgulama.isChecked(),self.güncelle.isChecked(),self.sil.isChecked()))
         self.windows.show()

     def Category2(self):
         self.windows3.close()
         self.windows=QWidget()
         self.Yazı5=QLabel("---Yapmak İstediğiniz İşlemi Seçiniz---")
         self.buton4=QPushButton("<")
         self.gosterme=QRadioButton("Kayıt Gösterme")
         self.ekleme=QRadioButton("Kayıt Ekleme")
         self.sorgulama=QRadioButton("Kayıt Sorgulama")
         self.güncelle=QRadioButton("Kayıdı Güncelle")
         self.sil=QRadioButton("Kayıdı Sil")
         self.buton3=QPushButton("Onayla")
         h_box=QHBoxLayout()
         v_box=QVBoxLayout()
         h_box.addWidget(self.buton4)

         #h_box.addWidget(self.buton5)
         v_box.addLayout(h_box)
         v_box.addWidget(self.Yazı5)
         v_box.addWidget(self.ekleme)
         v_box.addWidget(self.sorgulama)
         v_box.addWidget(self.güncelle)
         v_box.addWidget(self.sil)
         v_box.addStretch()
         v_box.addWidget(self.buton3)
         self.windows.setLayout(v_box)
         self.windows.setWindowTitle("İşlem Seçimi")
         self.buton4.clicked.connect(self.Entrance2)
         self.buton3.clicked.connect(lambda : self.Ogretmen(self.gosterme.isChecked(),self.ekleme.isChecked(),self.sorgulama.isChecked(),self.güncelle.isChecked(),self.sil.isChecked()))
         self.windows.show()

     def Category3(self):
         self.windows3.close()
         self.windows=QWidget()
         self.Yazı5=QLabel("---Yapmak İstediğiniz İşlemi Seçiniz---")
         self.buton4=QPushButton("<")
         self.gosterme=QRadioButton("Kayıtları Gösterme")
         self.ekleme=QRadioButton("Kayıt Ekleme")
         self.sorgulama=QRadioButton("Kayıt Sorgulama")
         self.güncelle=QRadioButton("Kayıdı Güncelle")
         self.sil=QRadioButton("Kayıdı Sil")
         self.buton3=QPushButton("Onayla")
         h_box=QHBoxLayout()
         v_box=QVBoxLayout()
         h_box.addWidget(self.buton4)
         v_box.addLayout(h_box)
         v_box.addWidget(self.Yazı5)
         v_box.addWidget(self.gosterme)
         v_box.addWidget(self.ekleme)
         v_box.addWidget(self.sorgulama)
         v_box.addWidget(self.güncelle)
         v_box.addWidget(self.sil)
         v_box.addStretch()
         v_box.addWidget(self.buton3)
         self.windows.setLayout(v_box)
         self.windows.setWindowTitle("İşlem Seçimi")
         self.buton4.clicked.connect(self.Entrance2)
         self.buton3.clicked.connect(lambda : self.Personel(self.gosterme.isChecked(),self.ekleme.isChecked(),self.sorgulama.isChecked(),self.güncelle.isChecked(),self.sil.isChecked()))
         self.windows.show()
     
     def Category4(self):
         self.windows4.close()
         self.windows=QWidget()
         self.Yazı5=QLabel("---Yapmak İstediğiniz İşlemi Seçiniz---")
         self.gosterme=QRadioButton("Kayıtları Göster")
         self.ekleme=QRadioButton("Kayıt Ekleme")
         self.sorgulama=QRadioButton("Kayıt Sorgulama")
         self.güncelle=QRadioButton("Kayıdı Güncelle")
         self.sil=QRadioButton("Kayıdı Sil")
         self.buton3=QPushButton("Onayla")
         self.buton4=QPushButton("<")
         h_box=QHBoxLayout()
         v_box=QVBoxLayout()
         h_box.addWidget(self.buton4)
         v_box.addLayout(h_box)
         v_box.addWidget(self.Yazı5)
         v_box.addWidget(self.ekleme)
         v_box.addWidget(self.sorgulama)
         v_box.addWidget(self.güncelle)
         v_box.addWidget(self.sil)
         v_box.addStretch()
         v_box.addWidget(self.buton3)
         self.windows.setLayout(v_box)
         self.windows.setWindowTitle("İşlem Seçimi")
         self.buton4.clicked.connect(self.Entrance2)
         self.buton3.clicked.connect(lambda : self.Ogrenci(self.gosterme.isChecked(),self.ekleme.isChecked(),self.sorgulama.isChecked(),self.güncelle.isChecked(),self.sil.isChecked()))
         self.windows.show()

     def Category5(self):
         self.windows4.close()
         self.windows=QWidget()
         self.Yazı5=QLabel("---Yapmak İstediğiniz İşlemi Seçiniz---")
         self.gosterme=QRadioButton("Kayıt Gösterme")
         self.ekleme=QRadioButton("Kayıt Ekleme")
         self.sorgulama=QRadioButton("Kayıt Sorgulama")
         self.güncelle=QRadioButton("Kayıdı Güncelle")
         self.sil=QRadioButton("Kayıdı Sil")
         self.buton3=QPushButton("Onayla")
         self.buton4=QPushButton("<")
         h_box=QHBoxLayout()
         v_box=QVBoxLayout()
         h_box.addWidget(self.buton4)
         
         v_box.addLayout(h_box)
         v_box.addWidget(self.Yazı5)
         v_box.addWidget(self.ekleme)
         v_box.addWidget(self.sorgulama)
         v_box.addWidget(self.güncelle)
         v_box.addWidget(self.sil)
         v_box.addStretch()
         v_box.addWidget(self.buton3)
         self.windows.setLayout(v_box)
         self.windows.setWindowTitle("İşlem Seçimi")
         self.buton4.clicked.connect(self.Entrance2)
         self.buton3.clicked.connect(lambda : self.Ogretmen(self.gosterme.isChecked(),self.ekleme.isChecked(),self.sorgulama.isChecked(),self.güncelle.isChecked(),self.sil.isChecked()))
         self.windows.show()

     def Category6(self):
         self.windows4.close()
         self.windows=QWidget()
         self.Yazı5=QLabel("---Yapmak İstediğiniz İşlemi Seçiniz---")
         self.gosterme=QRadioButton("Kayıtları Gösterme")
         self.ekleme=QRadioButton("Kayıt Ekleme")
         self.sorgulama=QRadioButton("Kayıt Sorgulama")
         self.güncelle=QRadioButton("Kayıdı Güncelle")
         self.sil=QRadioButton("Kayıdı Sil")
         self.buton3=QPushButton("Onayla")
         self.buton4=QPushButton("<")
         h_box=QHBoxLayout()
         v_box=QVBoxLayout()
         h_box.addWidget(self.buton4)
         v_box.addLayout(h_box)
         v_box.addWidget(self.Yazı5)
         v_box.addWidget(self.gosterme)
         v_box.addWidget(self.ekleme)
         v_box.addWidget(self.sorgulama)
         v_box.addWidget(self.güncelle)
         v_box.addWidget(self.sil)
         v_box.addStretch()
         v_box.addWidget(self.buton3)
         self.windows.setLayout(v_box)
         self.windows.setWindowTitle("İşlem Seçimi")
         self.buton4.clicked.connect(self.Entrance2)
         self.buton3.clicked.connect(lambda : self.Personel(self.gosterme.isChecked(),self.ekleme.isChecked(),self.sorgulama.isChecked(),self.güncelle.isChecked(),self.sil.isChecked()))
         self.windows.show()
         
     def Category7(self):
         self.windows7.close()
         self.windows=QWidget()
         self.Yazı5=QLabel("---Yapmak İstediğiniz İşlemi Seçiniz---")
         self.gosterme=QRadioButton("Kayıt Gösterme")
         self.ekleme=QRadioButton("Kayıt Ekleme")
         self.sorgulama=QRadioButton("Kayıt Sorgulama")
         self.güncelle=QRadioButton("Kayıdı Güncelle")
         self.sil=QRadioButton("Kayıdı Sil")
         self.buton3=QPushButton("Onayla")
         self.buton4=QPushButton("<")
         h_box=QHBoxLayout()
         v_box=QVBoxLayout()
         h_box.addWidget(self.buton4)
         v_box.addLayout(h_box)
         v_box.addWidget(self.Yazı5)
         v_box.addWidget(self.ekleme)
         v_box.addWidget(self.sorgulama)
         v_box.addWidget(self.güncelle)
         v_box.addWidget(self.sil)
         v_box.addStretch()
         v_box.addWidget(self.buton3)
         self.windows.setLayout(v_box)
         self.windows.setWindowTitle("İşlem Seçimi")
         self.buton4.clicked.connect(self.Entrance2)
         self.buton3.clicked.connect(lambda : self.Personel(self.gosterme.isChecked(),self.ekleme.isChecked(),self.sorgulama.isChecked(),self.güncelle.isChecked(),self.sil.isChecked()))
         self.windows.show()

     def Category8(self):
      self.windows7.close()
      self.windows8=QWidget()
      self.windows8.setWindowTitle("Personel Güncelleme İşlemleri")
      self.windows8.show()
      self.buton4=QPushButton("<")
      
      self.buton8=QRadioButton("Adı Değiştir")
      self.buton9=QRadioButton("Soyadı Değiştir")
      self.buton10=QRadioButton("TC Kimlik Numarasını Değiştir")
      self.buton11=QRadioButton("Doğum Tarihini Değiştir")
      self.buton12=QRadioButton("Tel Numarası Değiştir")
      self.buton13=QRadioButton("Görevini Değiştir")
      self.buton14=QPushButton("Onayla")
      h_box=QHBoxLayout()
      v_box=QVBoxLayout()
      h_box.addWidget(self.buton4)
      
      v_box.addLayout(h_box)
      v_box.addWidget(self.buton8)
      v_box.addWidget(self.buton9)
      v_box.addWidget(self.buton10)
      v_box.addWidget(self.buton11)
      v_box.addWidget(self.buton12)
      v_box.addWidget(self.buton13)
      v_box.addWidget(self.buton14)
      self.windows8.setLayout(v_box)
      self.buton4.clicked.connect(self.Guncelle)
      self.buton14.clicked.connect(lambda : self.Personel_Güncelleme(self.buton8.isChecked(),self.buton9.isChecked(),self.buton10.isChecked(),self.buton11.isChecked(),self.buton12.isChecked(),self.buton13.isChecked()))
      self.windows8.show()

     def Category9(self):
      self.windows7.close()
      self.windows8=QWidget()
      self.windows8.setWindowTitle("Öğretmen Güncelleme İşlemleri")
      self.windows8.show()
      self.buton4=QPushButton("<")
      
      self.buton8=QRadioButton("Adı Değiştir")
      self.buton9=QRadioButton("Soyadı Değiştir")
      self.buton10=QRadioButton("TC Kimlik Numarasını Değiştir")
      self.buton11=QRadioButton("Doğum Tarihini Değiştir")
      self.buton12=QRadioButton("Tel Numarası Değiştir")
      self.buton13=QRadioButton("Branşını Değiştir")
      self.buton14=QPushButton("Onayla")
      h_box=QHBoxLayout()
      v_box=QVBoxLayout()
      h_box.addWidget(self.buton4)
      
      v_box.addLayout(h_box)
      v_box.addWidget(self.buton8)
      v_box.addWidget(self.buton9)
      v_box.addWidget(self.buton10)
      v_box.addWidget(self.buton11)
      v_box.addWidget(self.buton12)
      v_box.addWidget(self.buton13)
      v_box.addWidget(self.buton14)
      self.windows8.setLayout(v_box)
      self.buton4.clicked.connect(self.Guncelle)
      self.buton14.clicked.connect(lambda : self.Ogretmen_Güncelleme(self.buton8.isChecked(),self.buton9.isChecked(),self.buton10.isChecked(),self.buton11.isChecked(),self.buton12.isChecked(),self.buton13.isChecked()))
      self.windows8.show()

     
     def Category11(self):
      self.windows7.close()
      self.windows8=QWidget()
      self.windows8.setWindowTitle("Öğrenci Güncelleme İşlemleri")
      self.windows8.show()
      self.buton4=QPushButton("<")
      
      self.buton8=QRadioButton("Adı Değiştir")
      self.buton9=QRadioButton("Soyadı Değiştir")
      self.buton10=QRadioButton("TC Kimlik Numarasını Değiştir")
      self.buton11=QRadioButton("Doğum Tarihini Değiştir")
      self.buton12=QRadioButton("Öğrenci Velisinin Tel Numarasını Değiştir")
      self.buton13=QRadioButton("Öğrencinin Okul Numarasını Değiştir")
      self.buton14=QPushButton("Onayla")
      h_box=QHBoxLayout()
      v_box=QVBoxLayout()
      h_box.addWidget(self.buton4)
      
      v_box.addLayout(h_box)
      v_box.addWidget(self.buton8)
      v_box.addWidget(self.buton9)
      v_box.addWidget(self.buton10)
      v_box.addWidget(self.buton11)
      v_box.addWidget(self.buton12)
      v_box.addWidget(self.buton13)
      v_box.addWidget(self.buton14)
      self.windows8.setLayout(v_box)
      self.buton4.clicked.connect(self.Guncelle3)
      self.buton14.clicked.connect(lambda : self.Ogrenci_Guncelleme(self.buton8.isChecked(),self.buton9.isChecked(),self.buton10.isChecked(),self.buton11.isChecked(),self.buton12.isChecked(),self.buton13.isChecked()))
      self.windows8.show()

     def Guncelle(self):
           self.windows8.close()
           self.windows7=QWidget()
           self.TC=QLabel("Personelin TC Kimlik Numarasını Yazınız: ")
           self.Tc4=QLineEdit()
           self.buton7=QPushButton("Sorgula")
           self.buton4=QPushButton("<")
           
           self.yazı_alanı4=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc4)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           v_box3.addWidget(self.yazı_alanı4)
           v_box3.addWidget(self.buton7)
           self.windows7.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category8)
           
           self.buton7.clicked.connect(self.sql7)
           self.windows7.setWindowTitle("Personel Güncelleme")
           self.windows7.show()
     def Guncelle2(self):
           self.windows7.close()
           self.windows11=QWidget()
           self.TC=QLabel("Öğretmenin TC Kimlik Numarasını Yazınız: ")
           self.Tc4=QLineEdit()
           self.buton7=QPushButton("Sorgula")
           self.buton4=QPushButton("<")
           
           self.yazı_alanı4=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc4)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           v_box3.addWidget(self.yazı_alanı4)
           v_box3.addWidget(self.buton7)
           self.windows11.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category9)
           
           self.buton7.clicked.connect(self.sql18)
           self.windows11.setWindowTitle("Öğretmen Kaydı Güncelleme")
           self.windows11.show()
     def Guncelle3(self):
           self.windows7.close()
           self.windows11=QWidget()
           self.TC=QLabel("Öğrencinin TC Kimlik Numarasını Yazınız: ")
           self.Tc4=QLineEdit()
           self.buton7=QPushButton("Sorgula")
           self.buton4=QPushButton("<")
           
           self.yazı_alanı4=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc4)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           v_box3.addWidget(self.yazı_alanı4)
           v_box3.addWidget(self.buton7)
           self.windows11.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category11)
           
           self.buton7.clicked.connect(self.sql25)
           self.windows11.setWindowTitle("Öğrenci Kaydı Güncelleme")
           self.windows11.show()

     def Guncelle4(self):
           self.windows8.close()
           self.windows7=QWidget()
           self.TC=QLabel("Personelin TC Kimlik Numarasını Yazınız: ")
           self.Tc4=QLineEdit()
           self.buton7=QPushButton("Sorgula")
           self.buton4=QPushButton("<")
           
           self.yazı_alanı4=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc4)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           v_box3.addWidget(self.yazı_alanı4)
           v_box3.addWidget(self.buton7)
           self.windows7.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category8)
           
           self.buton7.clicked.connect(self.sql7)
           self.windows7.setWindowTitle("Personel Güncelleme")
           self.windows7.show()
     def Guncelle5(self):
           self.windows9.close()
           self.windows11=QWidget()
           self.TC=QLabel("Öğretmenin TC Kimlik Numarasını Yazınız: ")
           self.Tc4=QLineEdit()
           self.buton7=QPushButton("Sorgula")
           self.buton4=QPushButton("<")
           
           self.yazı_alanı4=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc4)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           v_box3.addWidget(self.yazı_alanı4)
           v_box3.addWidget(self.buton7)
           self.windows11.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category9)
           
           self.buton7.clicked.connect(self.sql18)
           self.windows11.setWindowTitle("Öğretmen Kaydı Güncelleme")
           self.windows11.show()
     def Guncelle6(self):
           self.windows7.close()
           self.windows11=QWidget()
           self.TC=QLabel("Öğrencinin TC Kimlik Numarasını Yazınız: ")
           self.Tc4=QLineEdit()
           self.buton7=QPushButton("Sorgula")
           self.buton4=QPushButton("<")
           
           self.yazı_alanı4=QLabel()
           h_box14=QHBoxLayout()
           h_box13=QHBoxLayout()
           v_box3=QVBoxLayout()
           h_box14.addWidget(self.buton4)
           
           h_box13.addWidget(self.TC)
           h_box13.addWidget(self.Tc4)
           v_box3.addLayout(h_box14)
           v_box3.addLayout(h_box13)
           v_box3.addWidget(self.yazı_alanı4)
           v_box3.addWidget(self.buton7)
           self.windows11.setLayout(v_box3)
           self.buton4.clicked.connect(self.Category11)
           
           self.buton7.clicked.connect(self.sql25)
           self.windows11.setWindowTitle("Öğrenci Kaydı Güncelleme")
           self.windows11.show()

     def Personel_Güncelleme(self,ad,soyad,tc,dy,tel,gorev):
        if ad==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Name=QLabel("Yeni Adı:")
          self.New_Ad=QLineEdit()
          self.yazı_alanı5=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Name)
          h_box2.addWidget(self.New_Ad)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı5)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Personelin Adını Değiştirme")
          self.buton15.clicked.connect(self.sql8)
          self.buton4.clicked.connect(self.Category9)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()

        elif soyad==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Soyadı:")
          self.New_Soyad=QLineEdit()
          self.yazı_alanı6=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Soyad)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı6)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Personelin Soyadını Değiştirme")
          self.buton15.clicked.connect(self.sql9)
          self.buton4.clicked.connect(self.Category9)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif tc==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Tc Kimlik Numarası:")
          self.New_Tc=QLineEdit()
          self.yazı_alanı7=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.Guncelle)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Tc)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı7)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Personelin TC Kimlik Numarasını  Değiştirme")
          self.buton15.clicked.connect(self.sql10)
          self.buton4.clicked.connect(self.Guncelle4)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif dy==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Doğum Tarihi:")
          self.New_Dy=QLineEdit()
          self.yazı_alanı8=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Dy)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı8)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Personelin Doğum Tarihini Değiştirme")
          self.buton15.clicked.connect(self.sql11)
          self.buton4.clicked.connect(self.Category9)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif tel==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Cep Telefon Numarası:")
          self.New_Tel=QLineEdit()
          self.yazı_alanı9=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Tel)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı9)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Personelin Cep Telefon Numarasını Değiştirme")
          self.buton15.clicked.connect(self.sql12)
          self.buton4.clicked.connect(self.Category9)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
        elif gorev==1:
          self.windows8.close()
          self.windows9=QWidget()
          self.buton4=QPushButton("<")
          self.buton5=QPushButton(">")
          self.buton15=QPushButton("Onayla")
          self.New_Surname=QLabel("Yeni Görevi:")
          self.New_Gorev=QLineEdit()
          self.yazı_alanı10=QLabel("")
          h_box=QHBoxLayout()
          h_box2=QHBoxLayout()
          v_box=QVBoxLayout()
          h_box.addWidget(self.buton4)
          h_box.addWidget(self.buton5)
          h_box2.addWidget(self.New_Surname)
          h_box2.addWidget(self.New_Gorev)
          v_box.addLayout(h_box)
          v_box.addLayout(h_box2)
          v_box.addWidget(self.yazı_alanı10)
          v_box.addWidget(self.buton15)
          self.windows9.setLayout(v_box)
          self.windows9.setWindowTitle("Personelin Görevini Değiştirme")
          self.buton15.clicked.connect(self.sql13)
          self.buton4.clicked.connect(self.Category9)
          self.buton5.clicked.connect(self.Entrance5)
          self.windows9.show()
    
     def sql8(self):
      con3=sqlite3.connect("Personel.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Personel set Ad=? where Tc=?",(self.New_Ad.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Personel Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı5.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı5.setText("Ad Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Ad.clear()
        cursor3.execute("Update Personel set Ad=? where Tc=?",(self.New_Ad.text(),self.Tc4.text()))
        con3.commit()
      
     def sql9(self):
      con3=sqlite3.connect("Personel.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Personel set Soyad=? where Tc=?",(self.New_Soyad.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Personel Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı6.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı6.setText("Soyad Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Ad.clear()
        cursor3.execute("Update Personel set Soyad=? where Tc=?",(self.New_Soyad.text(),self.Tc4.text()))
        con3.commit()

     def sql10(self):
      con3=sqlite3.connect("Personel.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Personel set Tc=? where Tc=?",(self.New_Tc.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Personel Where Tc=?",(self.New_Tc.text(),))
      self.Tc4=self.New_Tc
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı7.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı7.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Tc.clear()
        cursor3.execute("Update Personel set Tc=? where Tc=?",(self.New_Tc.text(),self.Tc4.text()))
        con3.commit()

     def sql11(self):
      con3=sqlite3.connect("Personel.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Personel set Dy=? where Tc=?",(self.New_Dy.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Personel Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı8.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı8.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Tc.clear()
        cursor3.execute("Update Personel set Dy=? where Tc=?",(self.New_Dy.text(),self.Tc4.text()))
        con3.commit()
     
     def sql12(self):
      con3=sqlite3.connect("Personel.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Personel set Tel=? where Tc=?",(self.New_Tel.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Personel Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı9.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı9.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Tc.clear()
        cursor3.execute("Update Personel set Tel=? where Tc=?",(self.New_Tel.text(),self.Tc4.text()))
        con3.commit()

     def sql13(self):
      con3=sqlite3.connect("Personel.db")
      cursor3=con3.cursor()
      cursor3.execute("Update Personel set Gorev=? where Tc=?",(self.New_Gorev.text(),self.Tc4.text()))
      con3.commit()
      cursor3.execute("Select * From Personel Where Tc=?",(self.Tc4.text(),))
      kayıt=cursor3.fetchone()
      if kayıt!=None:
        self.yazı_alanı10.setText(str(kayıt))
        con3.close()
      else:
        self.yazı_alanı10.setText("TC Kimlik Numarası Değiştirme İşlemi Gerçekleştirilemedi.")
        self.New_Gorev.clear()
        cursor3.execute("Update Personel set Gorev=? where Tc=?",(self.New_Gorev.text(),self.Tc4.text()))
        con3.commit()

     def Entrance(self):
      self.windows3.close()
      self.windows2=QWidget()
      self.windows2.setWindowTitle("Okul Kaydı")
      self.windows2.setMinimumSize(300,300)
      self.Yazı=QLabel("Programa Hoşgeldiniz")
      self.Yazı2=QLabel(str(datetime.ctime(datetime.now())))
      self.Yazı3=QLabel("---Kategoriler---")
      self.Yazı4=QLabel("1-Öğrenci\n2-Öğretmen\n3-Personel")
      self.öğrenci=QRadioButton(" Öğrenci")
      self.öğretmen=QRadioButton(" Öğretmen")
      self.personel=QRadioButton(" Personel")
      self.buton=QPushButton("Onayla")
      v_box=QVBoxLayout()
      h_box=QHBoxLayout()
      v_box.addStretch()
      v_box.addWidget(self.Yazı)
      v_box.addWidget(self.Yazı2)
      v_box.addWidget(self.Yazı3)
      v_box.addWidget(self.Yazı4)
      v_box.addWidget(self.öğrenci)
      v_box.addWidget(self.öğretmen)
      v_box.addWidget(self.personel)
      v_box.addStretch()
      v_box.addWidget(self.buton)
      h_box.addStretch()
      h_box.addLayout(v_box)
      h_box.addStretch()
      h_box.maximumSize()
      self.windows2.setLayout(h_box)
      self.windows2.show()
      self.buton.clicked.connect(lambda : self.Kategori(self.öğrenci.isChecked(),self.öğretmen.isChecked(),self.personel.isChecked()))

     def Entrance2(self):
      self.windows.close()
      self.windows2=QWidget()
      self.windows2.setWindowTitle("Okul Kaydı")
      self.windows2.setMinimumSize(300,300)
      self.Yazı=QLabel("Programa Hoşgeldiniz")
      self.Yazı2=QLabel(str(datetime.ctime(datetime.now())))
      self.Yazı3=QLabel("---Kategoriler---")
      self.Yazı4=QLabel("1-Öğrenci\n2-Öğretmen\n3-Personel")
      self.öğrenci=QRadioButton(" Öğrenci")
      self.öğretmen=QRadioButton(" Öğretmen")
      self.personel=QRadioButton(" Personel")
      self.buton=QPushButton("Onayla")
      v_box=QVBoxLayout()
      h_box=QHBoxLayout()
      v_box.addStretch()
      v_box.addWidget(self.Yazı)
      v_box.addWidget(self.Yazı2)
      v_box.addWidget(self.Yazı3)
      v_box.addWidget(self.Yazı4)
      v_box.addWidget(self.öğrenci)
      v_box.addWidget(self.öğretmen)
      v_box.addWidget(self.personel)
      v_box.addStretch()
      v_box.addWidget(self.buton)
      h_box.addStretch()
      h_box.addLayout(v_box)
      h_box.addStretch()
      h_box.maximumSize()
      self.windows2.setLayout(h_box)
      self.windows2.show()
      self.buton.clicked.connect(lambda : self.Kategori(self.öğrenci.isChecked(),self.öğretmen.isChecked(),self.personel.isChecked()))

     def Entrance3(self):
      self.windows4.close()
      self.windows2=QWidget()
      self.windows2.setWindowTitle("Okul Kaydı")
      self.windows2.setMinimumSize(300,300)
      self.Yazı=QLabel("Programa Hoşgeldiniz")
      self.Yazı2=QLabel(str(datetime.ctime(datetime.now())))
      self.Yazı3=QLabel("---Kategoriler---")
      self.Yazı4=QLabel("1-Öğrenci\n2-Öğretmen\n3-Personel")
      self.öğrenci=QRadioButton(" Öğrenci")
      self.öğretmen=QRadioButton(" Öğretmen")
      self.personel=QRadioButton(" Personel")
      self.buton=QPushButton("Onayla")
      v_box=QVBoxLayout()
      h_box=QHBoxLayout()
      v_box.addStretch()
      v_box.addWidget(self.Yazı)
      v_box.addWidget(self.Yazı2)
      v_box.addWidget(self.Yazı3)
      v_box.addWidget(self.Yazı4)
      v_box.addWidget(self.öğrenci)
      v_box.addWidget(self.öğretmen)
      v_box.addWidget(self.personel)
      v_box.addStretch()
      v_box.addWidget(self.buton)
      h_box.addStretch()
      h_box.addLayout(v_box)
      h_box.addStretch()
      h_box.maximumSize()
      self.windows2.setLayout(h_box)
      self.windows2.show()
      self.buton.clicked.connect(lambda : self.Kategori(self.öğrenci.isChecked(),self.öğretmen.isChecked(),self.personel.isChecked()))
     
     def Entrance4(self):
      self.windows7.close()
      self.windows2=QWidget()
      self.windows2.setWindowTitle("Okul Kaydı")
      self.windows2.setMinimumSize(300,300)
      self.Yazı=QLabel("Programa Hoşgeldiniz")
      self.Yazı2=QLabel(str(datetime.ctime(datetime.now())))
      self.Yazı3=QLabel("---Kategoriler---")
      self.Yazı4=QLabel("1-Öğrenci\n2-Öğretmen\n3-Personel")
      self.öğrenci=QRadioButton(" Öğrenci")
      self.öğretmen=QRadioButton(" Öğretmen")
      self.personel=QRadioButton(" Personel")
      self.buton=QPushButton("Onayla")
      v_box=QVBoxLayout()
      h_box=QHBoxLayout()
      v_box.addStretch()
      v_box.addWidget(self.Yazı)
      v_box.addWidget(self.Yazı2)
      v_box.addWidget(self.Yazı3)
      v_box.addWidget(self.Yazı4)
      v_box.addWidget(self.öğrenci)
      v_box.addWidget(self.öğretmen)
      v_box.addWidget(self.personel)
      v_box.addStretch()
      v_box.addWidget(self.buton)
      h_box.addStretch()
      h_box.addLayout(v_box)
      h_box.addStretch()
      h_box.maximumSize()
      self.windows2.setLayout(h_box)
      self.windows2.show()
      self.buton.clicked.connect(lambda : self.Kategori(self.öğrenci.isChecked(),self.öğretmen.isChecked(),self.personel.isChecked()))

     def Entrance5(self):
      self.windows9.close()
      self.windows2=QWidget()
      self.windows2.setWindowTitle("Okul Kaydı")
      self.windows2.setMinimumSize(300,300)
      self.Yazı=QLabel("Programa Hoşgeldiniz")
      self.Yazı2=QLabel(str(datetime.ctime(datetime.now())))
      self.Yazı3=QLabel("---Kategoriler---")
      self.Yazı4=QLabel("1-Öğrenci\n2-Öğretmen\n3-Personel")
      self.öğrenci=QRadioButton(" Öğrenci")
      self.öğretmen=QRadioButton(" Öğretmen")
      self.personel=QRadioButton(" Personel")
      self.buton=QPushButton("Onayla")
      v_box=QVBoxLayout()
      h_box=QHBoxLayout()
      v_box.addStretch()
      v_box.addWidget(self.Yazı)
      v_box.addWidget(self.Yazı2)
      v_box.addWidget(self.Yazı3)
      v_box.addWidget(self.Yazı4)
      v_box.addWidget(self.öğrenci)
      v_box.addWidget(self.öğretmen)
      v_box.addWidget(self.personel)
      v_box.addStretch()
      v_box.addWidget(self.buton)
      h_box.addStretch()
      h_box.addLayout(v_box)
      h_box.addStretch()
      h_box.maximumSize()
      self.windows2.setLayout(h_box)
      self.windows2.show()
      self.buton.clicked.connect(lambda : self.Kategori(self.öğrenci.isChecked(),self.öğretmen.isChecked(),self.personel.isChecked()))
      
     def Entrance6(self):
      self.windows.close()
      self.windows2=QWidget()
      self.windows2.setWindowTitle("Okul Kaydı")
      self.windows2.setMinimumSize(300,300)
      self.Yazı=QLabel("Programa Hoşgeldiniz")
      self.Yazı2=QLabel(str(datetime.ctime(datetime.now())))
      self.Yazı3=QLabel("---Kategoriler---")
      self.Yazı4=QLabel("1-Öğrenci\n2-Öğretmen\n3-Personel")
      self.öğrenci=QRadioButton(" Öğrenci")
      self.öğretmen=QRadioButton(" Öğretmen")
      self.personel=QRadioButton(" Personel")
      self.buton=QPushButton("Onayla")
      v_box=QVBoxLayout()
      h_box=QHBoxLayout()
      v_box.addStretch()
      v_box.addWidget(self.Yazı)
      v_box.addWidget(self.Yazı2)
      v_box.addWidget(self.Yazı3)
      v_box.addWidget(self.Yazı4)
      v_box.addWidget(self.öğrenci)
      v_box.addWidget(self.öğretmen)
      v_box.addWidget(self.personel)
      v_box.addStretch()
      v_box.addWidget(self.buton)
      h_box.addStretch()
      h_box.addLayout(v_box)
      h_box.addStretch()
      h_box.maximumSize()
      self.windows2.setLayout(h_box)
      self.windows2.show()
      self.buton.clicked.connect(lambda : self.Kategori(self.öğrenci.isChecked(),self.öğretmen.isChecked(),self.personel.isChecked()))
app=QApplication(sys.argv)
pencere=Pencere()
app.setWindowIcon(QtGui.QIcon("Meb.png"))
sys.exit(app.exec_())

    